/**
 * @fileoverview gRPC-Web generated client stub for main
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.3.1
// 	protoc              v3.19.4
// source: communication/contract.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.main = require('./contract_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.main.ContractClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname;

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.main.ContractPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname;

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractCreateRequest,
 *   !proto.main.ContractResponse>}
 */
const methodDescriptor_Contract_Create = new grpc.web.MethodDescriptor(
  '/main.Contract/Create',
  grpc.web.MethodType.UNARY,
  proto.main.ContractCreateRequest,
  proto.main.ContractResponse,
  /**
   * @param {!proto.main.ContractCreateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractCreateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/Create',
      request,
      metadata || {},
      methodDescriptor_Contract_Create,
      callback);
};


/**
 * @param {!proto.main.ContractCreateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/Create',
      request,
      metadata || {},
      methodDescriptor_Contract_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.InviteDataRequest,
 *   !proto.main.InviteNub>}
 */
const methodDescriptor_Contract_InviteQuery = new grpc.web.MethodDescriptor(
  '/main.Contract/InviteQuery',
  grpc.web.MethodType.UNARY,
  proto.main.InviteDataRequest,
  proto.main.InviteNub,
  /**
   * @param {!proto.main.InviteDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.InviteNub.deserializeBinary
);


/**
 * @param {!proto.main.InviteDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.InviteNub)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.InviteNub>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.inviteQuery =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/InviteQuery',
      request,
      metadata || {},
      methodDescriptor_Contract_InviteQuery,
      callback);
};


/**
 * @param {!proto.main.InviteDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.InviteNub>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.inviteQuery =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/InviteQuery',
      request,
      metadata || {},
      methodDescriptor_Contract_InviteQuery);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ClaimContractRequest,
 *   !proto.main.ContractResponse>}
 */
const methodDescriptor_Contract_Claim = new grpc.web.MethodDescriptor(
  '/main.Contract/Claim',
  grpc.web.MethodType.UNARY,
  proto.main.ClaimContractRequest,
  proto.main.ContractResponse,
  /**
   * @param {!proto.main.ClaimContractRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractResponse.deserializeBinary
);


/**
 * @param {!proto.main.ClaimContractRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.claim =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/Claim',
      request,
      metadata || {},
      methodDescriptor_Contract_Claim,
      callback);
};


/**
 * @param {!proto.main.ClaimContractRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.claim =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/Claim',
      request,
      metadata || {},
      methodDescriptor_Contract_Claim);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.SignContractRequest,
 *   !proto.main.ContractResponse>}
 */
const methodDescriptor_Contract_Sign = new grpc.web.MethodDescriptor(
  '/main.Contract/Sign',
  grpc.web.MethodType.UNARY,
  proto.main.SignContractRequest,
  proto.main.ContractResponse,
  /**
   * @param {!proto.main.SignContractRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractResponse.deserializeBinary
);


/**
 * @param {!proto.main.SignContractRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.sign =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/Sign',
      request,
      metadata || {},
      methodDescriptor_Contract_Sign,
      callback);
};


/**
 * @param {!proto.main.SignContractRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.sign =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/Sign',
      request,
      metadata || {},
      methodDescriptor_Contract_Sign);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.QueryByIdRequest,
 *   !proto.main.ContractResponse>}
 */
const methodDescriptor_Contract_QueryById = new grpc.web.MethodDescriptor(
  '/main.Contract/QueryById',
  grpc.web.MethodType.UNARY,
  proto.main.QueryByIdRequest,
  proto.main.ContractResponse,
  /**
   * @param {!proto.main.QueryByIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractResponse.deserializeBinary
);


/**
 * @param {!proto.main.QueryByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.queryById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/QueryById',
      request,
      metadata || {},
      methodDescriptor_Contract_QueryById,
      callback);
};


/**
 * @param {!proto.main.QueryByIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.queryById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/QueryById',
      request,
      metadata || {},
      methodDescriptor_Contract_QueryById);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.QueryByUserRequest,
 *   !proto.main.ContractNubSet>}
 */
const methodDescriptor_Contract_QueryByUser = new grpc.web.MethodDescriptor(
  '/main.Contract/QueryByUser',
  grpc.web.MethodType.UNARY,
  proto.main.QueryByUserRequest,
  proto.main.ContractNubSet,
  /**
   * @param {!proto.main.QueryByUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractNubSet.deserializeBinary
);


/**
 * @param {!proto.main.QueryByUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractNubSet)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractNubSet>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.queryByUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/QueryByUser',
      request,
      metadata || {},
      methodDescriptor_Contract_QueryByUser,
      callback);
};


/**
 * @param {!proto.main.QueryByUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractNubSet>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.queryByUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/QueryByUser',
      request,
      metadata || {},
      methodDescriptor_Contract_QueryByUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestPrice,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestPrice = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestPrice',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestPrice,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestPrice} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestPrice} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestPrice =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestPrice',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestPrice,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestPrice} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestPrice =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestPrice',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestPrice);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactPrice,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactPrice = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactPrice',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactPrice,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactPrice} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactPrice} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactPrice =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactPrice',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactPrice,
      callback);
};


/**
 * @param {!proto.main.ContractReactPrice} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactPrice =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactPrice',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactPrice);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestDate,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestDate = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestDate',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestDate,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestDate} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestDate} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestDate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestDate',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDate,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestDate} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestDate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestDate',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactDate,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactDate = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactDate',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactDate,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactDate} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactDate} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactDate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactDate',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDate,
      callback);
};


/**
 * @param {!proto.main.ContractReactDate} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactDate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactDate',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestPayout,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestPayout = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestPayout',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestPayout,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestPayout} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestPayout} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestPayout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestPayout',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestPayout,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestPayout} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestPayout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestPayout',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestPayout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactPayout,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactPayout = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactPayout',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactPayout,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactPayout} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactPayout} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactPayout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactPayout',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactPayout,
      callback);
};


/**
 * @param {!proto.main.ContractReactPayout} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactPayout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactPayout',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactPayout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestItem,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestItem = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestItem',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestItem,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestItem',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestItem,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestItem',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactItem,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactItem = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactItem',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactItem,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactItem',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactItem,
      callback);
};


/**
 * @param {!proto.main.ContractReactItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactItem',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestAddItem,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestAddItem = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestAddItem',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestAddItem,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestAddItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestAddItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestAddItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestAddItem',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestAddItem,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestAddItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestAddItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestAddItem',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestAddItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactAddItem,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactAddItem = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactAddItem',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactAddItem,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactAddItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactAddItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactAddItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactAddItem',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactAddItem,
      callback);
};


/**
 * @param {!proto.main.ContractReactAddItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactAddItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactAddItem',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactAddItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestDelItem,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestDeleteItem = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestDeleteItem',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestDelItem,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestDelItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestDelItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestDeleteItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestDeleteItem',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDeleteItem,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestDelItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestDeleteItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestDeleteItem',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDeleteItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactDelItem,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactDeleteItem = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactDeleteItem',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactDelItem,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactDelItem} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactDelItem} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactDeleteItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactDeleteItem',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDeleteItem,
      callback);
};


/**
 * @param {!proto.main.ContractReactDelItem} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactDeleteItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactDeleteItem',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDeleteItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestAddDeadline,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestAddDeadline = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestAddDeadline',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestAddDeadline,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestAddDeadline} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestAddDeadline} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestAddDeadline =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestAddDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestAddDeadline,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestAddDeadline} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestAddDeadline =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestAddDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestAddDeadline);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactAddDeadline,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactAddDeadline = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactAddDeadline',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactAddDeadline,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactAddDeadline} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactAddDeadline} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactAddDeadline =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactAddDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactAddDeadline,
      callback);
};


/**
 * @param {!proto.main.ContractReactAddDeadline} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactAddDeadline =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactAddDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactAddDeadline);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestDelDeadline,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestDeleteDeadline = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestDeleteDeadline',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestDelDeadline,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestDelDeadline} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestDelDeadline} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestDeleteDeadline =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestDeleteDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDeleteDeadline,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestDelDeadline} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestDeleteDeadline =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestDeleteDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDeleteDeadline);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactDelDeadline,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactDeleteDeadline = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactDeleteDeadline',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactDelDeadline,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactDelDeadline} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactDelDeadline} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactDeleteDeadline =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactDeleteDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDeleteDeadline,
      callback);
};


/**
 * @param {!proto.main.ContractReactDelDeadline} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactDeleteDeadline =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactDeleteDeadline',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDeleteDeadline);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractSuggestDeadlineItems,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_SuggestDeadlineItems = new grpc.web.MethodDescriptor(
  '/main.Contract/SuggestDeadlineItems',
  grpc.web.MethodType.UNARY,
  proto.main.ContractSuggestDeadlineItems,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractSuggestDeadlineItems} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractSuggestDeadlineItems} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.suggestDeadlineItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/SuggestDeadlineItems',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDeadlineItems,
      callback);
};


/**
 * @param {!proto.main.ContractSuggestDeadlineItems} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.suggestDeadlineItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/SuggestDeadlineItems',
      request,
      metadata || {},
      methodDescriptor_Contract_SuggestDeadlineItems);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.main.ContractReactDeadlineItems,
 *   !proto.main.ContractEditResponse>}
 */
const methodDescriptor_Contract_ReactDeadlineItems = new grpc.web.MethodDescriptor(
  '/main.Contract/ReactDeadlineItems',
  grpc.web.MethodType.UNARY,
  proto.main.ContractReactDeadlineItems,
  proto.main.ContractEditResponse,
  /**
   * @param {!proto.main.ContractReactDeadlineItems} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.main.ContractEditResponse.deserializeBinary
);


/**
 * @param {!proto.main.ContractReactDeadlineItems} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.main.ContractEditResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.main.ContractEditResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.main.ContractClient.prototype.reactDeadlineItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/main.Contract/ReactDeadlineItems',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDeadlineItems,
      callback);
};


/**
 * @param {!proto.main.ContractReactDeadlineItems} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.main.ContractEditResponse>}
 *     Promise that resolves to the response
 */
proto.main.ContractPromiseClient.prototype.reactDeadlineItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/main.Contract/ReactDeadlineItems',
      request,
      metadata || {},
      methodDescriptor_Contract_ReactDeadlineItems);
};


module.exports = proto.main;

